namespace ARudzbenik.Data
{
    public enum Lesson
    {
        NO_LESSON = 0,
        SUSTAV_VIDEOIGARA_ZA_VISE_IGRACA = 1,
        OPTIMIZACIJA_I_PROGRAMIRANJE_VIDEOIGRE_ZA_VISE_IGRACA_NA_ISTOM_UREDAJU = 2,
        OPTIMIZACIJA_I_PROGRAMIRANJE_VIDEOIGRE_ZA_VISE_IGRACA_PUTEM_LOKALNE_MREZE = 3,
        OPTIMIZACIJA_I_PROGRAMIRANJE_VIDEOIGRE_ZA_VISE_IGRACA_PUTEM_INTERNETA = 4,
    }
}